# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - run: docker build -t voltor . 

      # run tests!
      - run: docker run voltor npm test

  deploy-qa:
    working_directory: ~/app
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Deploy to now.sh
          command: sh deployments/qa.sh

  deploy-prd:
    working_directory: ~/app
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints: 
          - "46:82:97:83:87:ef:52:a9:da:4c:5d:0c:46:2f:32:10"
      - run:
          name: Deploy to PRD
          command: sh deployments/prd.sh

workflows:
  version: 2
  buildi-and-deploy:
    jobs:
      - build
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: /feature_.*/
      - deploy-prd:
          requires:
            - build
          filters:
            branches:
              only: master

