# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/node:7.10

    steps:
      - checkout
      - setup_remote_docker

      - run: docker build -t voltor . 

      # run tests!
      - run: docker run voltor npm test
      
      - deploy:
          name: Deploy qa
          command: sh deployments/qa.sh
